# TODO: Write the tasks check module to check all local files after each synchronization and assert that all of them are
#  PRIORG assignments; If any VTODO was not an assignment, this module should turn it into one...
